repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    # Linter
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    # Formatter (substitui black)
    -   id: ruff-format
        
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        
-   repo: https://github.com/pycqa/pylint
    rev: v2.17.4
    hooks:
    -   id: pylint
